# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import dlframework_pb2 as dlframework__pb2


class RegistryStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.FrameworkManifests = channel.unary_unary(
        '/carml.org.dlframework.Registry/FrameworkManifests',
        request_serializer=dlframework__pb2.FrameworkRequest.SerializeToString,
        response_deserializer=dlframework__pb2.FrameworkManifestsResponse.FromString,
        )
    self.FrameworkAgents = channel.unary_unary(
        '/carml.org.dlframework.Registry/FrameworkAgents',
        request_serializer=dlframework__pb2.FrameworkRequest.SerializeToString,
        response_deserializer=dlframework__pb2.Agents.FromString,
        )
    self.ModelManifests = channel.unary_unary(
        '/carml.org.dlframework.Registry/ModelManifests',
        request_serializer=dlframework__pb2.ModelRequest.SerializeToString,
        response_deserializer=dlframework__pb2.ModelManifestsResponse.FromString,
        )
    self.ModelAgents = channel.unary_unary(
        '/carml.org.dlframework.Registry/ModelAgents',
        request_serializer=dlframework__pb2.ModelRequest.SerializeToString,
        response_deserializer=dlframework__pb2.Agents.FromString,
        )


class RegistryServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def FrameworkManifests(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FrameworkAgents(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ModelManifests(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ModelAgents(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RegistryServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'FrameworkManifests': grpc.unary_unary_rpc_method_handler(
          servicer.FrameworkManifests,
          request_deserializer=dlframework__pb2.FrameworkRequest.FromString,
          response_serializer=dlframework__pb2.FrameworkManifestsResponse.SerializeToString,
      ),
      'FrameworkAgents': grpc.unary_unary_rpc_method_handler(
          servicer.FrameworkAgents,
          request_deserializer=dlframework__pb2.FrameworkRequest.FromString,
          response_serializer=dlframework__pb2.Agents.SerializeToString,
      ),
      'ModelManifests': grpc.unary_unary_rpc_method_handler(
          servicer.ModelManifests,
          request_deserializer=dlframework__pb2.ModelRequest.FromString,
          response_serializer=dlframework__pb2.ModelManifestsResponse.SerializeToString,
      ),
      'ModelAgents': grpc.unary_unary_rpc_method_handler(
          servicer.ModelAgents,
          request_deserializer=dlframework__pb2.ModelRequest.FromString,
          response_serializer=dlframework__pb2.Agents.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'carml.org.dlframework.Registry', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class PredictorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Predict = channel.unary_unary(
        '/carml.org.dlframework.Predictor/Predict',
        request_serializer=dlframework__pb2.PredictRequest.SerializeToString,
        response_deserializer=dlframework__pb2.PredictResponse.FromString,
        )


class PredictorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Predict(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PredictorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Predict': grpc.unary_unary_rpc_method_handler(
          servicer.Predict,
          request_deserializer=dlframework__pb2.PredictRequest.FromString,
          response_serializer=dlframework__pb2.PredictResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'carml.org.dlframework.Predictor', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
