FROM nvcr.io/nvidia/pytorch:19.06-py3

# Build-time metadata as defined at http://label-schema.org
ARG BUILD_DATE
ARG VCS_REF
ARG VCS_URL
ARG VERSION
ARG ARCH
ARG FRAMEWORK_VERSION
LABEL org.pytorch.agent.build-date=$BUILD_DATE \
      org.pytorch.agent.name="pytorch agent" \
      org.pytorch.agent.description="" \
      org.pytorch.agent.url="https://www.mlmodelscope.org/" \
      org.pytorch.agent.vcs-ref=$VCS_REF \
      org.pytorch.agent.vcs-url=$VCS_URL \
      org.pytorch.agent.vendor="MLModelScope" \
      org.pytorch.agent.version=$VERSION \
      org.pytorch.agent.schema-version="1.0"

# Install Go
ENV GIMME_GO_VERSION "1.12"
ENV GIMME_OS "linux"
ENV GIMME_ARCH $ARCH

LABEL org.golang.version=$GIMME_GO_VERSION
LABEL org.golang.os=$GIMME_OS
LABEL org.golang.arch=$GIMME_ARCH

ADD https://raw.githubusercontent.com/travis-ci/gimme/master/gimme /usr/bin/gimme
RUN chmod +x /usr/bin/gimme
RUN gimme

ENV GOROOT "/root/.gimme/versions/go${GIMME_GO_VERSION}.${GIMME_OS}.${GIMME_ARCH}"
ENV PATH ${GOROOT}/bin:${PATH}

ENV GOPATH "/go"
ENV PATH $GOPATH/bin:$PATH
ENV LD_LIBRARY_PATH /usr/local/cuda/extras/CUPTI/lib64:$LD_LIBRARY_PATH

# Install Go packages
RUN go get -u github.com/golang/dep/cmd/dep

# Get Go bindings
ENV PKG github.com/rai-project/pytorch
WORKDIR $GOPATH/src/$PKG

RUN git clone --depth=1 --branch=master https://${PKG}.git .

RUN dep ensure -v -no-vendor -update \
    github.com/rai-project/go-pytorch \
    github.com/rai-project/go-echarts \
    github.com/rai-project/dlframework \
    github.com/rai-project/evaluation && \
    dep ensure -v -vendor-only

ENV CGO_CFLAGS "${CGO_CFLAGS} -I /opt/conda/lib/python3.6/site-packages/torch/include -I /opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include"

ENV CGO_CXXFLAGS "${CGO_CXXFLAGS} -I /opt/conda/lib/python3.6/site-packages/torch/include -I /opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include"

ENV CGO_LDFLAGS "${CGO_LDFLAGS} -L /opt/conda/lib/python3.6/site-packages/torch/lib"

RUN go build -a -installsuffix cgo -ldflags "-s -w -X ${PKG}/Version=${VERSION} -X ${PKG}/GitCommit=${VCS_REF} -X ${PKG}/BuildDate=${BUILD_DATE}"&& \
    cd pytorch-agent && \
    go install && \
    cd .. && \
    rm -fr vendor

ENTRYPOINT ["pytorch-agent"]
