FROM carml/go-pytorch:amd64-gpu-latest

# Build-time metadata as defined at http://label-schema.org
ARG BUILD_DATE
ARG VCS_REF
ARG VCS_URL
ARG VERSION
ARG ARCH
ARG FRAMEWORK_VERSION
LABEL org.pytorch.agent.build-date=$BUILD_DATE \
      org.pytorch.agent.name="pytorch agent" \
      org.pytorch.agent.description="" \
      org.pytorch.agent.url="https://www.mlmodelscope.org/" \
      org.pytorch.agent.vcs-ref=$VCS_REF \
      org.pytorch.agent.vcs-url=$VCS_URL \
      org.pytorch.agent.vendor="MLModelScope" \
      org.pytorch.agent.version=$VERSION \
      org.pytorch.agent.schema-version="1.0"


# Get Go bindings
ENV PKG github.com/rai-project/pytorch
WORKDIR $GOPATH/src/$PKG

RUN git clone --depth=1 --branch=master https://${PKG}.git .

RUN dep ensure -v -no-vendor -update \
    github.com/rai-project/go-pytorch \
    github.com/rai-project/go-echarts \
    github.com/rai-project/dlframework \
    github.com/rai-project/evaluation \
    github.com/rai-project/tracer && \
    dep ensure -v -vendor-only

ENV LD_LIBRARY_PATH="/usr/local/cuda/lib64/stubs:${LD_LIBRARY_PATH}"

RUN ln -s /usr/local/cuda-10.1/targets/x86_64-linux/lib/stubs/libnvidia-ml.so /usr/local/cuda-10.1/targets/x86_64-linux/lib/stubs/libnvidia-ml.so.1 && ldconfig

RUN go build -a -installsuffix cgo -ldflags "-s -w -X ${PKG}/Version=${VERSION} -X ${PKG}/GitCommit=${VCS_REF} -X ${PKG}/BuildDate=${BUILD_DATE}"&& \
    cd pytorch-agent && \
    go install && \
    cd ..

ENTRYPOINT ["pytorch-agent"]
